name: Add label

on:
  pull_request:
    types: [opened, edited, reopened, labeled]

jobs:
  log-context:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
  reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: "Send Review Request"
        if: github.actor == 'joaquin-ruiz-masmovil'
        uses: kunihiko-t/review-request-action@v0.1.3
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          reviewers: "fothdev"
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        if: ${{ github.actor == 'joaquin-ruiz-masmovil' }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['mas-consents']
            })
