name: Github Action to choose PR template by Actor

on:
  pull_request:
    path:
    - '**.md'

jobs:
  pull-request:
    if: |
      (
        (github.actor == 'joaquin-ruiz-masmovil') ||
        (github.actor == 'fothdev')
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: GitHub Pull Request Action
        uses: repo-sync/pull-request@v2.3
        with:
          destination_branch: "master"                      # If blank, default: master
          pr_title: "feat(mas-consents | api): MCONS-..."   # Title of pull request
          pr_template: ".github/PULL_REQUEST_TEMPLATE/pull_request_version_template.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
          pr_reviewer: "joaquin-ruiz-masmovil,fothdev"      # Comma-separated list (no spaces)
          pr_assignee: "joaquin-ruiz-masmovil,fothdev"      # Comma-separated list (no spaces)
          pr_label: "mas-consents"                          # Comma-separated list (no spaces)
          pr_draft: true                                    # Creates pull request as draft
          pr_allow_empty: false                             # Creates pull request even if there are no changes
          github_token: "${{ secrets.GITHUB_TOKEN }}"
